[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install --upgrade pip"]

[phases.build]
cmds = [
    "pip install -r requirements.txt",
    "python manage.py collectstatic --no-input",
    "python manage.py migrate"
]

[start]
cmd = "gunicorn pipsmade.wsgi:application --bind 0.0.0.0:$PORT" 