# Generated by Django 5.2.2 on 2025-08-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='manual_profit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profit added manually by admin', max_digits=12),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total profit (manual + calculated)', max_digits=12),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='total_withdrawable',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount user can withdraw (investment + profit)', max_digits=12),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='total_withdrawable',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount user can withdraw (investment + profit)', max_digits=15),
        ),
    ]
