# Generated by Django 5.2.2 on 2025-08-16 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_userinvestment_manual_profit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='manual_profit_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total manual profit given by admin', max_digits=15),
        ),
        migrations.CreateModel(
            name='ManualProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Profit amount to give to user', max_digits=12)),
                ('description', models.CharField(help_text='Reason for giving this profit', max_length=255)),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this profit is still active')),
                ('given_by', models.ForeignKey(blank=True, help_text='Admin who gave this profit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profits_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_profits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-given_at'],
            },
        ),
    ]
