# Generated by Django 5.2.2 on 2025-08-16 17:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_userportfolio_manual_profit_total_manualprofit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestment',
            name='investment_plan',
            field=models.ForeignKey(blank=True, help_text='Standard investment plan', null=True, on_delete=django.db.models.deletion.CASCADE, to='investments.investmentplan'),
        ),
        migrations.CreateModel(
            name='AdminInvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Custom name for this investment plan', max_length=100)),
                ('plan_type', models.CharField(choices=[('crypto', 'Cryptocurrency'), ('stocks', 'Stock Market'), ('forex', 'Forex Trading'), ('bonds', 'Bonds & Fixed Income'), ('custom', 'Custom Plan')], default='custom', max_length=20)),
                ('description', models.TextField(help_text='Description of this custom plan')),
                ('min_investment', models.DecimalField(decimal_places=2, default=100.0, max_digits=12)),
                ('max_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('roi_percentage', models.DecimalField(decimal_places=2, help_text='Fixed ROI percentage for this plan', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Duration in days')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is active')),
                ('features', models.JSONField(blank=True, default=list, help_text='Custom features for this plan')),
                ('special_terms', models.TextField(blank=True, help_text='Special terms and conditions')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='admin_investment_plan',
            field=models.ForeignKey(blank=True, help_text='Admin-created custom investment plan', null=True, on_delete=django.db.models.deletion.CASCADE, to='investments.admininvestmentplan'),
        ),
    ]
