# Generated by Django 5.2.2 on 2025-08-18 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='Email address to send notifications to', max_length=254)),
                ('notify_login', models.BooleanField(default=True, help_text='Send email when users log in')),
                ('notify_signup', models.BooleanField(default=True, help_text='Send email when new users register')),
                ('notify_deposits', models.BooleanField(default=True, help_text='Send email when users make deposit requests')),
                ('notify_withdrawals', models.BooleanField(default=True, help_text='Send email when users make withdrawal requests')),
                ('notify_support', models.BooleanField(default=True, help_text='Send email when users submit support tickets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(help_text='Admin user who will receive email notifications', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Email Configuration',
                'verbose_name_plural': 'Admin Email Configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
