# Generated by Django 5.2.2 on 2025-08-29 19:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('market', 'Market Analysis'), ('price', 'Price Action'), ('regulation', 'Regulation'), ('adoption', 'Adoption & Partnerships'), ('technology', 'Technology & Development'), ('defi', 'DeFi & NFTs'), ('trading', 'Trading & Volume'), ('general', 'General News')], default='general', max_length=20)),
                ('related_coins', models.JSONField(default=list, help_text='List of related cryptocurrency symbols')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1, help_text='Higher number = higher priority')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('featured_image', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Crypto News',
                'verbose_name_plural': 'Crypto News',
                'ordering': ['-published_at', '-priority'],
                'indexes': [models.Index(fields=['-published_at'], name='crypto_news_publish_49746a_idx'), models.Index(fields=['category'], name='crypto_news_categor_e6e96a_idx'), models.Index(fields=['sentiment'], name='crypto_news_sentime_8822a4_idx'), models.Index(fields=['is_active'], name='crypto_news_is_acti_d13e0b_idx')],
            },
        ),
    ]
